server:
  port: 8081

spring:
  application:
    name: users-api
  datasource:
    url: ${DB_USERS_RDS_URL}
    username: ${DB_USERS_RDS_USERNAME}
    password: ${DB_RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "App to retrieve users"
appVersion: "1.0.0"

aws:
  cognito:
    clientId: 7ob2a627tkpjou1tn4rtt1vj2l
    userPoolId: us-east-2_EFzNkvd5I
    region: us-east-2
    connectionTimeout: 2000
    readTimeout: 2000
    identityPoolUrl: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_EFzNkvd5I
    jwk: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_EFzNkvd5I/.well-known/jwks.json
    issuer: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_EFzNkvd5I
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}